### ISSUE TITLE
[카테고리] 영문웹진 (콘텐츠 분류 / static page 메뉴)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#10]
[카테고리] - 콘텐츠 영문 명칭 관련

- 인터뷰: Interview
- 에세이: Essay
- 논평: Critical Review
- 좌담: Research Forum
- 자료해제: Document Review

[static page]
- 연구소 소개 :  https://github.com/team-durumi/kyeol/issues/23
- 웹진 결 소개 : https://github.com/team-durumi/kyeol/issues/26
- 위안부 용어 소개 : https://github.com/team-durumi/kyeol/issues/24

[디자인 화면]
- http://kyeol-en.durumi.io/html-en/05_basic_list.html

* 하단에 작은 아이콘으로 전체보기, 엮어보기, Glossary 가 들어가면 좋겠다.

**Comment by woonjjang** [comment]
(Menu) 
- 인터뷰: Interview
- 에세이: Essay
- 논평: Critical Review
- 좌담: Research Forum
- 자료해제: Document Review
- Sort by – Person / Subject / Region / Writer / Glossary

뉴스레터(영문에서는 뉴스레터 적용 안 함)
Receive news and updates on the Webzine Kyeol.
Provide your email address / Request Newsletter

**Comment by woonjjang** [comment]
(Menu)명칭 수정 -11월 26일 수정 @mozodev 

### node category
- 인터뷰: Interview
- 에세이: Essay
- 논평: Comment
- 좌담: Discussion
- 자료해제: Bibliographical Explanation
- Sort by – Person / Subject / Region / Writer / Glossary

### 
- 자료실 : Resource
- 소개 : About

**Comment by woonjjang** [comment]
http://kyeol.durumi.io/en/admin/structure/taxonomy/article_category
카테고리 term 들 번역 추가해 놓았습니다.

**Comment by woonjjang** [comment]
http://www.kyeol.kr/en/%EA%B8%B0%EC%82%AC-%EB%B6%84%EB%A5%98/interview

all 화면을 제외하고 나머지는 taxonomy에서 불러오는 화면이라 영문쪽 글만 불러와야 할 것 같아요. 
"기사-분류" - Taxonomy는 번역필드가 없어서, 국문까지 변할까봐 바꿔놓진 못했습니다.

**Comment by mozodev** [comment]
http://www.kyeol.kr/en/%EA%B8%B0%EC%82%AC-%EB%B6%84%EB%A5%98/interview 
이제 영문만 보여줍니다.
뷰에서 언어 필터만 추가하면 됨

**Comment by woonjjang** [comment]
잘 나오는 듯 !!
