### ISSUE TITLE
[영문] 자료실 / Resource - 영문 신규(국문에는 없음)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#11]
- http://kyeol-en.durumi.io/html-en/05_resources_list.html
- 영문 관계된 자료들을 올려놓는 곳으로 사용하려고 함.

**Comment by mozodev** [comment]
- 제목
- 본문
- 이미지
- 첨부파일

**Comment by woonjjang** [comment]
article과 동일한 css 출력되도록만 잡아주시면 감사하겠습니다. 
http://www.kyeol.kr/en/resources
