### ISSUE TITLE
메인 (추가 고객 피드백) / Header

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#13]
최종 : http://kyeol-en.durumi.io/html-en/00_main_06.html
---------
1. 메인 최종안

-최종안 슬라이드 하단 3개의 창 부분("Comfort Women", RIMSS, Webzine KYEOL)에 아래 예시와 같이 제목+작은 사진(연구소 제공 예정)+소개글(1-2문장) 구성으로 수정 가능 여부 알려주시면 감사하겠습니다.

또한 소개글이 끝나는 지점에 ...read more. 삽입 후 클릭 시 이동 기능 추가 가능한지도 확인 부탁드리겠습니다.
하단 콘텐츠 노출: 카테고리(총 5개) 별로 2개씩 노출, 발행일 순. 제목 위에 Edition, Essay등의 작은 네모 상자는 삭제하기로 하였습니다. 추후 반영 부탁드리겠습니다.

 

![창 예시](https://user-images.githubusercontent.com/6022883/100183520-7bf55000-2f22-11eb-9c29-d18dcf4dd5eb.png)

>> 이 부분은 상단에 슬라이드 (이미지) 영역이 있어서 올리고 나면 이상할 것 같아 보이긴 해요. (read more)

**Comment by woonjjang** [comment]
- 테마 작업할 때 능력부족으로 아이콘을 넣지 못했습니다. 만들어 놓은 아이콘 공유합니다. (KR 텍스트로 처리)
- 국문테마에는 EN 버튼( 클릭시 kyeol.durumi.io/en)
- 영문테마에는 KR 버튼( 클릭시 kyeol.durumi.io/kr)
![kr-icon](https://user-images.githubusercontent.com/6022883/100299864-0946ac00-2fd8-11eb-902d-b96e75e49ea8.png)
![en-icon](https://user-images.githubusercontent.com/6022883/100299869-0a77d900-2fd8-11eb-8ba3-88727a45d236.png)

**Comment by woonjjang** [comment]
@mozodev 메인에 필요하실 것 같아서 영문 번역 글 생성했습니다. 

아시겠지만 메인 노출설정을 하던 관리화면 :  http://kyeol.durumi.io/en/admin/webzine
노출글들이 메인 Sticky 설정이 되어 있어서 4개 글 "Promoted t' front page" 설정하고 저장해 놨습니다. 

http://kyeol.durumi.io/en/node/138
http://kyeol.durumi.io/en/node/139
http://kyeol.durumi.io/en/node/160
http://kyeol.durumi.io/en/node/133

**Comment by woonjjang** [comment]
![스크린샷 2020-11-27 오후 5 58 00](https://user-images.githubusercontent.com/6022883/100431467-8eff5000-30db-11eb-8942-836abd56fee1.png)

- "Comfort Women"
- About (마우스over 했을 때 rimss / kyeol  선택할 수 있게 해 달라던 요청)
- Content(Article)
- Resource (신규 콘텐츠 타입)

>> about 페이지 탭으로 분리하는 것은 차후 스타일 적용 때 하시죠.

**Comment by mozodev** [comment]
연구소에서 사진받은 게 없으면 처음 사진 넣는 것은 나중에 할께요 ㅎ

**Comment by woonjjang** [comment]
<img width="615" alt="스크린샷 2020-11-29 오후 12 08 45" src="https://user-images.githubusercontent.com/6022883/100530948-c2f18700-323b-11eb-899b-30ea10a1c706.png">
푸터 이메일 노출 영역에 (이메일 가려지는 부분 확인부탁드려요)

**Comment by mozodev** [comment]
이제 개발 서버보시면 안되고요. 운영서버 보세요. 개발서버에는 클라우드플레어가 앞에 있어서 자동으로 치환합니다. 사용하기 싫으면 proxy 전체를 끄면 됩니다만 ㅎ

**Comment by woonjjang** [comment]
넵 (마이너한 이슈라, 고객은 얘기하겠죠. ㅎㅎ)

**Comment by mozodev** [comment]
개발서버로 보고하실꺼에요? 저는 운영서버로 하는줄? 손가락으로 클릭만 하면 끌 수 있는... ㅍㅎㅎ

**Comment by woonjjang** [comment]
모조님 의견대로 운영서버로 하시죠. (KR 버튼을 대신 완료보고 이후에 달아주는 것으로)

**Comment by woonjjang** [comment]
@mozodev 메인 node 글 노출 부분에 글 모든 카테고리가 노출되는 것은 맞죠 ? (영역별 제목 나오는 부분은 없애달라고 했었음.)

**Comment by mozodev** [comment]
http://kyeol-en.durumi.io/html-en/00_main_06.html 이게 최종아닌가요? 맨 위에 적어놓으셨... 제목에 있는 세개만 노출... ㅎ 전 들은 적 없음...

**Comment by mozodev** [comment]
영문에 KR 버튼은 달려있는데요 http://www.kyeol.kr/en
국문에 EN 버튼을 달면 사이드 메뉴가 없어지는데... 국문에도 영문처럼 메뉴를 추가해야하나요? 이건 결정이 안된듯...

**Comment by woonjjang** [comment]
죄송해요. 
- 영역별 제목 나오는 부분은 고객이 없애달라고 했었는데, 요건 보여줬다가 피드백 받고 빼면 좋겠어요. 
- 카테고리는 전체가 노출되는게 맞습니다. "하단 콘텐츠 노출: 카테고리(총 5개) 별로 2개씩 노출, 발행일 순. 제목 위에 Edition, Essay등의 작은 네모 상자는 삭제하기로 하였습니다.

**Comment by woonjjang** [comment]
> 영문에 KR 버튼은 달려있는데요 http://www.kyeol.kr/en
> 국문에 EN 버튼을 달면 사이드 메뉴가 없어지는데... 국문에도 영문처럼 메뉴를 추가해야하나요? 이건 결정이 안된듯...

국문에는 메뉴 유지하고 KR 버튼이 하나 추가되는 방식입니다. 
영문에도 모바일쪽 화면 정리는 한 번 해야 하는 상황입니다.

**Comment by mozodev** [comment]
KR 버튼 위치는요? 검색 옆 완전 오른쪽?

**Comment by woonjjang** [comment]
<img width="386" alt="스크린샷 2020-11-29 오후 12 28 52" src="https://user-images.githubusercontent.com/6022883/100531941-7d828900-323e-11eb-8e55-8c35e68c2fd1.png">
위치는 여기

**Comment by woonjjang** [comment]
@mozodev 고생하셨습니다.  메인은 우선 종료 !
