### ISSUE TITLE
세부 글 Style - NODE

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#14]
디자인 : http://kyeol-en.durumi.io/html-en/01_node.html
2. 폰트, 자간, 단락간격

- 본문세부글 폰트는 sans-serif가 더 나은 것 같다고 의견이 모아졌습니다.
- 다만 현재 세부페이지의 자간이 조금 넓은 것 같다는 의견이 있어 아래 예시와 같이 조금 좁혀주시면 감사하겠습니다.

https://grad.ucla.edu/admissions/
https://www.ohchr.org/EN/Issues/Slavery/SRSlavery/Pages/SRSlaveryIndex.aspx 
https://sfi.usc.edu/about

**Comment by woonjjang** [comment]
![스크린샷 2020-11-29 오후 12 42 48](https://user-images.githubusercontent.com/6022883/100532812-75c3e400-3240-11eb-977f-3bb615f55762.png)

@mozodev 테섭에서 영문 편집화면에서는 taxanomy field들 설정하는 곳이 있었는데요. 실섭에는 없네요. (왠지 같은 영역이어서, 번역만 들어가 있으면 자동으로 나오게 해주실 것 같기도 한데, 확인 부탁드려요 ~)

**Comment by mozodev** [comment]
아 공통이라서 뺐어요.
12:46
사실 어떤 필드를 영문과 국문이 값을 다르게할지 정해야하는데 제가 볼때는 제목 본문만 하면 될 듯 하여 나머지는 국문의 값을 그대로 쓰는데 taxonomy term 이나 노드 레퍼런스의 경우 번역을 하면 그 값이 보이니까 괜찮을 듯요 ㅎ

**Comment by woonjjang** [comment]
http://www.kyeol.kr/en/node/133 하나 입력했습니다. 
>> http://www.kyeol.kr/en/ 홈이랑 http://www.kyeol.kr/en/category/articles node 목록 한 번 확인이 필요할 듯 (썸네일 부분)

**Comment by mozodev** [comment]
뷰 설정을 아직 안해서 그런거였는데 수정했어요.. 옆에 한글은 메뉴에서 번역하면 됩니다.

**Comment by woonjjang** [comment]
[수정사항]
위에서 부터 눈에보이는 국문 단어만 변경하면 좋을 것 같습니다. (이건 나중에 고객이 바꾸자고 할 수 도 있을 듯)
- [x] 2018년 (영문쪽 호수 링크로 변경 http://www.kyeol.kr/en/vol/2018 ) 
- [x] Essay (http://www.kyeol.kr/en/%EA%B8%B0%EC%82%AC-%EB%B6%84%EB%A5%98/essay)
- [x] 공유버튼 - 영문 공유버튼 클릭시에 영문 url 설정이 필요합니다. [국문url 설정](https://github.com/team-durumi/kyeol-composer/commit/028e08c5981aafd40ca26e73226b2f1ca7d6dcf7)
- [x] 상단의 호수링크 / article 분류 버튼 확인
- [ ] 관련인물, 관련지역, 전문용어 :  Person /  Region / Writer / Glossary
- [ ] 하단부 글 끝나는 부분 - Tag:  Subject
- [x] 참고문헌 Ref.

**Comment by mozodev** [comment]
- [x] 관련인물, 관련지역, 전문용어 : Person / Region / Writer / Glossary
제가 몇개 둘러봤는데 번역된것들은 잘 출력이 되는데요.
이상한곳이 있으면 링크를 남겨주세요. 확인이 어려워요.
>> 출력에는 이상이 없습니다. 
>> 클릭했을 때 도달하는 타겟 링크가 국문쪽이어서 생기는 이슈입니다. (http://www.kyeol.kr/archive/person?search=Bae%20Bong-ki )

- [x] 하단부 글 끝나는 부분 - Tag: Subject
http://www.kyeol.kr/ko/node/133
http://kyeol.kr/ko/taxonomy/term/291/translate
증언자들 태그도 모두 번역해야 영어로 나옵니다. (OK)
>> 출력에는 이상이 없습니다. 
>> 클릭했을 때 도달하는 타겟 링크가 국문쪽이어서 생기는 이슈입니다. 

- [x] 참고문헌 -- 이 필드도 번역 필드로 추가해놓지 않았는데.. 추가하겠다하면 번역 필드로 설정하고 일일이 번역을 해야합니다.
http://www.kyeol.kr/ko/node/133
http://www.kyeol.kr/en/node/133

>> 참고문헌은 고객에게 국영문 통일해서 영문으로 넣어야 한다고 완료보고 때 설명했어요.(일일이 번역하시기 어려울 것으로 보여서)

**Comment by mozodev** [comment]
일단 링크에 누락되어 있던 영문 주소를 추가했음
