### ISSUE TITLE
키워드 제목 앞에 ' 등의 특수기호가 있을 경우 전문용어 팝업창 제목이 짤림

### ISSUE THREAD

**Issue by mozodev** [team-durumi/kyeol-composer#2]
http://www.kyeol.kr/node/202
#개인통보제도 가 전문용어로 등록되었는데, 전문용어로 표시되지 않습니다.

문장 첫 시작 시 검색되지 않는 known issue

**Comment by mozodev** [comment]
3. 그리고 전문용어 내용 중 “(겹따옴표)가 있는 경우 내용이 잘리는 것 같습니다. (duplicate)

**Comment by notbadfutures** [comment]
* http://www.kyeol.kr/node/179 - 전문용어 꼬임 / 군속 / 아시아태평양전쟁 한국인 희생자 보상청구사건 - 전문용어 내 “ 이후 내용 텍스트 짤림. “(따옴표)를 지우니 팝업 내용 보임 
* http://www.kyeol.kr/node/224 - 미국 연방회의 일본군’위안부’ 사죄 결의안,  #2015년 한일 '위안부' 합의, 팝업창 제목 짤림. - 단어가 긴 경우에 짤리는 듯.  혹은 제목에 ‘ 가 있어서??
* http://www.kyeol.kr/node/202 - 개인통보제도 / 팝업 기능 구현 x
* http://www.kyeol.kr/node/183 - 한일 청구권협정 3조 / 팝업 기능 구현 x - 텍스트가 꼬인 듯. 아마 팝업 안에 전문용어 키워드가 같은 단어가 있어서 그런 듯? - 전문용어 키워드 내용을 수정하니 해결..
*  http://www.kyeol.kr/node/161 - 제국의 위안부 - 팝업창 짤림 / 일제 강제징용 배상 판결 - 팝업 기능 구현 x
* http://www.kyeol.kr/node/203 - 1936년 나가사키 지방 재판소 판결 / 팝업창 내용 안뜸 / 전문용어 내용이 “ 시작해서 그런 듯. “를 삭제하니 정상 작동
* http://www.kyeol.kr/node/149 - 제국의 위안부 - 팝업창 내용 짤림 / 키워드 앞 특수기호 짤림 
* http://www.kyeol.kr/node/197 - 이에나가부로.. - 팝업창 내용 짤림 / 일화평화조약 - 팝업창 내용 꼬임 - 임시 삭제
