### ISSUE TITLE
국문쪽 슬라이드 

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#20]
- 영문쪽 영향인 듯 ?
- 웹진 결 메인페이지 슬라이드 기능

**Comment by mozodev** [comment]
<img width="800" alt="스크린샷 2020-12-01 오전 12 03 50" src="https://user-images.githubusercontent.com/1661950/100626139-c59dca80-3368-11eb-8b7a-6e5bd96952a5.png">

현재 국문 슬라이드 이미지 파일 아이디가 888, 889, 890인데 첫번째 것만 888만 있고 두 개가 삭제됐음..
코드 상 이미지가 없으면 출력 안함... 
디비 백업본에서 파일 아이디  889, 890을 찾아서 복원했는데 확인 결과 파일도 삭제되서... 백업본에서 찾아서 다시 업로드했음
