### ISSUE TITLE
[국문] 메뉴 추가 - 뉴스레터

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#21]
(현승인 PM 요청)
- 결 뉴스레터 발송하고 있는데 (스티비)
- HTML 전체를 그대로 복붙해서 뉴스레터를 저장할 수 있는 메뉴 요청
- 신규 콘텐츠타입을 만들고, "전체보기"아래 "뉴스레터" 메뉴로 하나 추가되면 됩니다. 

(결 운영유지 쪽에서 요청한 이슈)
- https://github.com/team-durumi/kyeol/issues/3
- https://github.com/team-durumi/kyeol/issues/27

**Comment by mozodev** [comment]
http://www.kyeol.kr/ko/newsletters

**Comment by woonjjang** [comment]
괜찮은데요. ^^ 고생하셨습니다.
