### ISSUE TITLE
[3월작업]뉴스레터 구독자 수집, 목록 조회, 엑셀 다운로드, 감사 이력 조회

### ISSUE THREAD

**Issue by mozodev** [team-durumi/kyeol-composer#30]
장기적으로 봤을 때 웹진 결 사이트 내에서 직접 웹진 결 뉴스레터 구독자 이메일 정보가 저장되는 게 
관리 차원에서 좋을 것 같다는 판단을 진흥원 정보관리팀과 연구소에서 내렸습니다.

구체적으로 저희가 원하는 기능은

1. 웹진 결 뉴스레터 구독하기 버튼을 누르면 신규 구독자 이메일 주소가 스티비가 아니라 웹진 결 사이트 내에 수집되도록 할 것
2. 특정 관리자 계정으로 접속 시 웹진 결 사이트에 접속 시 뉴스레터 이메일 주소에 접근할 수 있을 것
3. 위의 특정 관리자 계정이 이메일 주소에 접근한 시기, 이메일 주소를 다운로드 받거나 삭제한 기록 등이 로그로 남을 것입니다.

**Comment by mozodev** [comment]
1. 뉴스레터 구독
홈페이지에서 구독 신청하면 우선 데이터베이스에 기록하고 스티비 API를 활용해서 스티비에 저장합니다.
어렵지 않게 구현 가능.

스티비 구독자 API 확인 완료
https://api.stibee.com/docs/


2. 특정 관리자 계정 뉴스레터 이메일 조회와 관련해서...
3. 이메일 주소 화면 로그는 좀 세부사항들이 있는데
목록 화면에 이메일 주소를 그대로 보여주면 사실 개별 이메일 주소에 모두 해당 관리자가 이 시간에 메일주소를 봤다는 로그를 남겨야해서
복잡해집니다. 다운로드만 기록하는게 현실적인데 그러면 전체 이메일 주소를 봤다고 로그를 남길 수 있습니다.

**Comment by woonjjang** [comment]
견적 발송 / 계약 확인 후 진행 : [견적서  링크](https://drive.google.com/file/d/1C3lm3yvf1R29Y5c-2KwbwVbyYhUq-h--/view?usp=sharing)

**Comment by woonjjang** [comment]
[고객에게 한 번 더 확인 요청해서 받은내용]

구체적으로 저희가 원하는 기능은

1. 웹진 결 뉴스레터 구독하기 버튼을 누르면 신규 구독자 이메일 주소가 스티비가 아니라 웹진 결 사이트 내에 수집되도록 할 것

2. 특정 관리자 계정으로 접속 시 웹진 결 사이트에 접속 시 뉴스레터 이메일 주소에 접근할 수 있을 것

3. 위의 특정 관리자 계정이 이메일 주소에 접근한 시기, 이메일 주소를 다운로드 받거나 삭제한 기록 등이 로그로 남을 것

----------

어제 보내드렸던 <웹진 결 뉴스레터 구독자 이메일 정보 수집 개발 관련 상세 내용>

이메일에 이어 좀 더 상세한 내용 메일 드립니다.

첫 번째 첨부파일인 <접속기록점검_기능 관련 메뉴> 파일 내의 캡처 이미지가 현재 한국여성인권진흥원 뉴스레터 구독자 이메일 정보가 수집되고 관리되는 화면의 캡처 이미지인데요. 웹진 결 내 구독자 이메일 정보 수집 시에도 이러한 형태로 개발이 진행되면 좋겠습니다.  

그리고 두 번째 첨부파일은 월별 접속기록 점검 보고 양식인데요, 이 양식 내용 참고하여 개발 진행해주시면 될 것 같아요.

**Comment by mozodev** [comment]
1 관련해서 이메일 수집은 홈페이지에 하는데 앞으로도 이메일 발송은 스티비로 계속하는게 맞겠죠? 
그러면 자동으로 스티비에도 저장되도록 하는게 편할텐데요. 
홈페이지에만 쌓으면 매번 엑셀로 다운받아서 스티비에다가 추가해줘야하는데.... 이건 고객이 이해하고 있겠죠?

**Comment by woonjjang** [comment]
옙. 여러번 고객한테 설명하긴했습니다. 발송은 스티비로 계속한다.  / 수동으로 엑셀로 넣겠다.

**Comment by mozodev** [comment]
[audit-log-report.pdf](https://github.com/team-durumi/kyeol-composer/files/6227490/audit-log-report.pdf)
[stibee-examples.pdf](https://github.com/team-durumi/kyeol-composer/files/6227493/stibee-examples.pdf)

**Comment by woonjjang** [comment]
[중간공유]

1. 이메일 수집 : kyeol.kr 메인에서 이메일을 입력하고, 저장하면 스티비에서 저장되던 것에서 kyeol 내부 이메일 목록으로 이동한다. (최종 확인 후 변경 개발)

2. 메일링리스트 관리(개발완료)
> 2.1. list-emails : 개별추가, import기능을 통해서 스티비에서 받은 목록을 업로드 한다. 
> 2.2. add email : 이메일 개별 추가한다. 
> 2.3. import-emails : CSV 목록을 이메일 리스트에 업로드한다. 
> 2.4. export list : CSV 목록으로 발송 목록을 다운로드 한다. 
> 2.5. rename-list / del-list : 목록을 추가하거나, 삭제한다. 

3. 메일링스트 관리 내역(audit log)
> 3.1. 메일링리스트 관리 내역 (완료)
> 3.2. 이메일 목록에서 변경 이슈 발생시 내역 확인(개발중)

4. 뉴스레터 발송시(예상)
> 4.1. 이메일 export list를 받아서, 매월 뉴스레터 발송 시점에 스티비에 업로드한다. 
> 4.2. 이메일 발송한다. 
> 4.3. 이메일 발송 이후에 스티비에서 정보보호를 위해 삭제한다. 

[확인 및 협의해야 하는 이슈]

1. 수신거부(unsubscribe) : 사용자들이 받은 이메일에서 구독취소를 누르게 되면, 스티비의 목록에서 구독취소 됨. / 목록 협의
> 1.1. 자동으로 이메일에 포함되는 뉴스레터 탈퇴 메뉴를 없앤다.
> 1.2. 이메일에 탈퇴 버튼을 누르면 웹진결 사이트쪽 링크로 연결되어서 엑셀 목록에서 삭제될 수 있도록 연결하는 개발(추가 필요)
> 결론적으로 구독취소(탈퇴)관련된 시나리오를 상호 확인하는게 필요합니다.

**Comment by woonjjang** [comment]
[04.16]
- 뉴스레터 입력 하면 / 뉴스테러 폼에 연결되도록 넣은 상황
- (4월 26일) 감사 관련 이슈가 있다. / 5월 뉴스레터 발송

[수신거부 이슈]
- 치환할 수 있는 링크로 변경해서 뉴스레터 구독취소 / 삭제 부분 까지 테스트를 

[올해]
- 한 달에 한 번씩 이런 이슈가 있거나 / 없는 것을 월별 유지보수 보고서
- 7월 정도 합쳐서 진행하면 된다.

**Comment by woonjjang** [comment]
[사용자 이메일 자동 구독취소 방법]

[이메일 목록]
- 이메일 목록에서 다운로드를 하면 해당 이메일과 함께 사용자별 토큰값 목록이 함께 엑셀로 다운로드 됩니다. 
- 주소록 필드에서 토큰(token)이라는 필드를 추가해서 이메일 / 이름 / 토큰 3개 필드를 기준으로 주소록에 업로드 합니다.
- 이메일에 자동구독취소 링크를 제외하고 구독취소 버튼을 추가합니다. 혹은 구독취소 텍스트에 링크를 겁니다. 
- 구독취소 링크는 사용자별로 아래 링크를 클릭해야 결(드루팔)시스템에서 사용자를 확인하고, 목록에서 구독취소를 진행합니다. 
- 해당 취소 기록이 결(드루팔) 시스템에도 남습니다. 

[넣어야 하는 링크]
- http://kyeol.kr/mailing-list/unsubscribe/?token=$%token%$ 


[방식]
- (샘플)http://kyeol.kr/mailing-list/unsubscribe/?token=czoyNzoiM3x0ZWFtQGR1cnVtaS5pb3wxNjE4NTU5NTMzIjs
- (사용자별)http://kyeol.kr/mailing-list/unsubscribe/?token=사용자토큰

[링크]
- (스티비에 샘플 콘텐츠 띄워놨습니다.) https://stibee.com/email/525289/edit/step05
- (주소록 샘플 목록)https://stibee.com/lists/115604/subscribers/S/all
