### ISSUE TITLE
[영문] 8월에 오픈 / 국문 편집팀 연계

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#36]
- 담당자 : 신은지 연구원
- 4월말에서 5월초 쯤 미팅 요청할 수 있음. (6월에 관련된 인사이동 문제를 처리해야 겠지)

[국문] 변은지 담당자
- 외주 : 

[영문] 신은지 연구원
- 영문쪽 SEO
- 웹쪽 번역 덜 되어 있는 것 확인

**Comment by woonjjang** [comment]
@mozodev 13일 ~ 17일 사이에 국문팀에서도 미팅을 요청하긴 했어요. 오픈아카이브 제안 발표나 행정일정 겹칠 것 같아서 약속은 우선 안 잡았어요. 제주 일정이 혹시 겹칠까 해서, 제주 일정 잡히면 한 번 공유해주세요 ~

**Comment by mozodev** [comment]
12일(수) ~ 14일(금)!
