### ISSUE TITLE
[SSL 설치] kyeol.kr (26-27일)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#37]
- [x] 디버그용 코드삭제 https://github.com/team-durumi/kyeol-composer/commit/c18d92a71ff9ca1629dafaa73b33d9e09c9f9ac5
- [x] SSL 설치 -  여성가족부 정보화 사업 감사 때문에 진흥원 지식정보팀에서 웹진 결 사이트 내에 SSL 보안서버 인증서를 설치요청  / 일단 가비아에서 제공하는 SSL 보안서버 인증서   Sectigo Basic  부가세 포함 44,000원 상품 (행정처리 및 구매 완료되면 27일 쯤 진행

**Comment by mozodev** [comment]
https://kyeol.kr/
