### ISSUE TITLE
메일링 리스트 관리내역에서 나타나는 ip 주소 값이  실제 ip 주소와 다르게 보여지는 오류

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#43]
다름이 아니라 웹진 결 사이트 내에서 이메일 주소를 export 할 시, 메일링 리스트 관리내역에서 나타나는 ip 주소 값이

실제 ip 주소와 다르게 보여지는 오류가 확인되어 메일 드립니다.

진흥원 지식정보팀 측에서 캡처 이미지 내의 ip는 다 해외에서 다운로드 받은 것으로 나온다고 합니다.

이 부분 다시 한 번 확인해주시고 회신 주시면 고맙겠습니다.

![hiworks_20210603_7005](https://user-images.githubusercontent.com/6022883/120961078-0f43f380-c798-11eb-8ec5-311bc7a8f4a8.PNG)

**Comment by mozodev** [comment]
cloudflare ip 가 찍히는군요 ㅎ
https://support.cloudflare.com/hc/en-us/articles/206776727-Understanding-the-True-Client-IP-Header

**Comment by woonjjang** [comment]
Cloudflare ->  cafe24 기본 네임서버로 이동하기로 했어요.
