### ISSUE TITLE
[국문]메일링리스트관리내역 메뉴 사용자 권한 수정

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#44]
현재는 한운장 개발자님, 홍영택 개발자님의 아이디로도 뉴스레터 구독자 정보를 다운로드(export)받을 수 있게 되어 있는데요,

진흥원 지식정보팀 담당자께서 다운로드는 진흥원 내부 직원의 아이디로만 가능하게,

외부 아이디로는 다운로드가 안 되게 막아달라고 하셨는데요.

메일링리스트관리내역 메뉴에 아예 접근이 안 되게 해주시면 좋을 것 같습니다.

일단 평소엔 이렇게 막아두고 만약 뉴스레터 구독자 정보수집기능 개발 관련해서 추가 요청드릴 일이 생기면 그때만 임시로 접근이 가능하게 풀어주셔도 좋을 것 같아요.

곧 웹진 수행업체분들께도 아이디를 생성해드려야 해서 그 분들의 아이디도 마찬가지로 메일링리스트관리내역 메뉴에 아예 접근이 안 되게 해주시면 좋을 것 같습니다.

이 부분은 빠르게 적용이 가능한지 궁금합니다.

**Comment by mozodev** [comment]
현재도 관리자 역할이 있는 9개 계정만 메뉴에 접근이 가능합니다.
비활성화되어 있던 편집자 역할 계정을 활성화시킨 후 로그인해서 확인 완료...

**Comment by woonjjang** [comment]
<img width="1440" alt="role=editor" src="https://user-images.githubusercontent.com/6022883/122858245-f10ff300-d354-11eb-8a48-c9d796818192.png">

권한 관련
- editor 권한으로는 editor 메뉴들만 접근가능하게 해 두었습니다. 
- 뉴스레터 목록 접근 확인하는 최상위 관리자들만 admin으로 해 두고, 나머지는 모두 editor로 변경하면 됩니다. (캡쳐 2개 보냅니다.)
- 개발팀은 권한과 관련없이 / DB나 역할지정과 관련없이 접근할 수 있는 방법이 있습니다. 따라서, 완전히 접근이 안 되게 한다는 부분은 시스템상으로 불가능합니다.
