### ISSUE TITLE
이메일 목록 다운로드 에러 (신규 구독자데이터 csv 포함 안 되는 문제)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#45]
보내드린 캡처이미지를 보시면 현재 시점 기준 279번까지 구독자가 있는데요,

export를 눌러서 다운로드 받은 csv 파일을 보면 

원본 셀이 import로 되어있는, 개발 테스트 시 직접 넣었던 기존 구독자들 외에

직접 웹진 결 사이트에서 구독신청해주신 신규구독자 분들(272번부터)의 정보는 csv파일로 다운로드가 되지 않습니다.

그리고 캡처이미지에 보시면 ID 270번 위가 271번이 아니라 272번인데요 , 

이렇게 한 칸이 벌어지는 것은 어떤 이유에서인지(구독했다가 구독취소를 하면 그 칸이 비는 걸까요?) 모르겠는데 바로잡아주시면 좋겠습니다.

>> 다음주 화요일에 회신하기로 했음. (메일에 포함되어 있는 기타 등등 요청은 거절)

**Comment by mozodev** [comment]
그럼 월요일에 살펴보겠... 아마도 헤더가 날라간걸가요? 메일을 봐도 무슨 소리인지 잘 모르겠...

**Comment by mozodev** [comment]
확인 결과 정상적으로 잘 받아짐...
