### ISSUE TITLE
[웹접근 심사] 웹진 결 국영문

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#47]
- 검사기관 : http://wa.or.kr/
- 신청 후 평가 : 10일 -> 작업 대응 :10일

현재 웹진 운영사인 퍼플레이에서 관련된 작업 정산

**Comment by css3studio** [comment]
https://docs.google.com/spreadsheets/d/1gVuDwBqadfANoDWaRXhW104ehByASTzSpcm6-_o7pKM/edit#gid=0
접근성 작업테이블입니다

**Comment by css3studio** [comment]
전체적으로 검진을 해보니, 포스트 내에 < > 기호가 들어간 부분이 상당히 많고, 대부분의 오류가 여기서 발생하고 있습니다.
개발자 한분이 sql명령어로 전체 컨텐츠내 <>를 html용 특수코드 &#60; &#62;로 변경해 주실 수 있을까요? -> 작성자,포스트제목,내용에 모두 포함됨
아니면, php에서 저걸 치환해서 출력해 주어야 할거 같습니다.

![image](https://user-images.githubusercontent.com/30469662/127836666-7c5951bb-499e-4910-ada3-84d323845a41.png)

![image](https://user-images.githubusercontent.com/30469662/127836232-7594fad0-eb1b-473a-91c6-0a92fbbecea3.png)

![image](https://user-images.githubusercontent.com/30469662/127835708-422c1dc0-f956-42f4-b327-bdf113a82010.png)

**Comment by css3studio** [comment]
소스 수정하고 푸시하였는데요. 서버에는 어떻게 적용시키나요? 혹시 개발 서버가 있나요?

**Comment by woonjjang** [comment]
@css3studio 결 채널에 서버 적용 요청하시면 모조님이 도와주실꺼에요.

**Comment by mozodev** [comment]
일단 서버에 적용은 했어요. 제가 확인을 할 수 없어서... 이후에 진행할게 있으면 진행하시죠 ㅎ

**Comment by woonjjang** [comment]
퍼플레이팀 확인

1. 모든 항목에 점수가 95점이 넘어야 한다.
> 현재 심사 결과, 퍼플레이팀이 1 / 5 /  9 / 14 / 15 수정

2. 빨간색 엑스 두개를 받은 항목은 반드시 전체 페이지를 수정해야 한다 
> 1  / 9  / 14 / 15 해당

3. 일정은 8월 23일까지 연장

**Comment by css3studio** [comment]
우선 제가 처리할 수 있는것은 다 처리하고, 이슈테이블에 정리해 두었습니다. 개발자/컨텐츠 처리사항 완료된 후 검수 및 추가 수정들어가겠습니다. 두분도 이슈테이블 확인하셔서 처리하시고 알려주시기 바랍니다.

**Comment by mozodev** [comment]
https://docs.google.com/spreadsheets/d/1gVuDwBqadfANoDWaRXhW104ehByASTzSpcm6-_o7pKM/edit#gid=113507056

## 전문가 상세보고서

- [x] 2 | 중 | 전체>푸터 | http://www.kyeol.kr/ | 푸터로고 이미지의 ALT에 이미지의 텍스트와 동일한 대체텍스트 제공
- [x] 3	| 상 |	전체/메인	http://www.kyeol.kr/	메인화면 > 에세이 논평 헤드라인등 모든 출력되는 이미지의 ALT속성에 대체텍스트 설명 제공,이미지의 용도를 알 수 있도록 대체텍스트에 해당 설명이나 정보를 제공해야 함.
- [x] 4	| 중 |	전체>헤더	http://www.kyeol.kr/	로고이미지 > 정보를 가지는 배경이미지에 대해 이미지와 동등한 대체콘텐츠를 제공해야 함.
- [x]  14    | 중  |       인터뷰>컨텐트 | https://www.kyeol.kr/ko/node/261  https://kyeol.kr/ko/node/212 | 키보드 초점의 정상적인 이동을 위해 모든이미지 영역의 H2 > A태그를 삭제 바람. 
- [x] 17    | 상 |			주요컨텐츠로 건너뛰기' -> '본문 바로가기' 문구수정
- [x] 19 | 상 | 엮어보기>주제>#국제사회(목록) | https://www.kyeol.kr/ko/archive/tags/?search=국제사회회 | 페이지 제목 분류가 더 가능함에도 상위 범주로 제목을 제공한 경우:페이지의 내용에 맞는 세분화된 페이지 타이틀을 제공해야 함.

## 사용자 심사보고서

- [ ] 4	| 상 |	홈>인터뷰>일제강점기로의 시간 여행, 상상해본 적 있나요? - 『푸른 늑대의 파수꾼전맹 』김은진 작가 인터뷰		"- 상세 내용 페이지에서 사진 이미지 링크의 대체텍스트에 JPG와 같은 파일 확장자가 있어서는 안 됨.- 모든 상세 페이지에서 제공된 ""SUP  [1]"", ""SUP [2]"" 링크들의 용도를 알수 없음. a태그에 title=""""을 넣어 용도를 지정해 줘야 함 다른 페이지들도 동일하게 적용"
- [x] 5	| 상 |	홈> 에세이>일본인 ‘위안부’ 다미 씨 이야기		"- 첫 번째 이미지에 제공된 alt 가 적절하지 않음. ""홈페이지_메인.jpg"" - 파일 확장자 제공 관련 오류 사항은 이전 과업과 동일." https://kyeol.kr/ko/node/419  퍼플레이 콘텐츠 팀이 수정중

**Comment by mozodev** [comment]
```html
# 각주 위치
<sup data-footnote-id="ou4g2"><a href="#footnote-1" id="footnote-marker-1-1" rel="footnote" title="각주 보기">[1]</a></sup></p>
# 각주 내용
<ol><li data-footnote-id="ou4g2" id="footnote-1"><a href="#footnote-marker-1-1" title="각주 위치로 돌아가기">^</a> <cite>본문 중 '일본군 강제 위안부'라고 표기된 부분은, 일본군‘위안부’를 지창하는 작가 개인의 고유한 표혐임.</cite></li>
```

콘텐츠 편집자가 임의로 해당 부분 마크업을 수정해도
콘텐츠 편집 화면 진입 시 ckeditor footnote/plugin.js 가 해당 부분 html을 교체합니다. 
그러니까 콘텐츠 편집자가 마크업을 수정해도 (이것도 사실 현실성이 없는 시나리오)... 반영되지 않습니다.

**Comment by woonjjang** [comment]
[콘텐츠 팀 회신]

웹진 <결> 접근성 인증 심사 작업을 위한 콘텐츠 수정 작업이 일단락 되어 공유드립니다. 
​
아래 목록의 콘텐츠들은 헤더 이미지 사진이 저희에게 없어 연구소에 요청한 상태이고,
이 콘텐츠들을 제외하면, 우선 수정작업은 모두 마무리되었습니다.
제대로 수정되었을 지 전체적으로 점검 한 번 해주시면 감사하겠습니다!
(지난 메일에서, 수정 샘플을 엑셀파일로 첨부하여 보내드렸는데 확인하셨을지 모르겠어요. 함께 살펴봐주시길 부탁드립니다.)

변경 적용한 것 (지난 메일에서, 수정 샘플을 엑셀파일로 첨부하여 보내드렸는데 확인하셨을지 모르겠어요. 함께 살펴봐주시길 부탁드립니다.)
>> https://kyeol.kr/ko/node/332
>> https://www.kyeol.kr/ko/node/201

​
*잔여
​[좌담]
https://kyeol.kr/ko/node/201
https://kyeol.kr/ko/node/161
​
[에세이]
https://kyeol.kr/ko/node/241
https://kyeol.kr/ko/node/240
https://kyeol.kr/ko/node/213
​
[논평]
https://kyeol.kr/ko/node/174
https://kyeol.kr/ko/node/156
​
@css3studio 현민님 잔여 항목을 제외하고 나머지 항목들 랜덤하게 확인부탁드려요. 저도 좀 살펴보겠습니다.

**Comment by woonjjang** [comment]
@mozodev 뉴스레터 kyeol site 쪽 html 삭제해도 됩니다.

**Comment by mozodev** [comment]
```bash
# 완료
$ mv /var/www/kyeol-composer/web/sites/defulat/files/newsletters/ /data/kyeol/
```

**Comment by css3studio** [comment]
전체적으로 페이지 검수하여 이슈테이블에 남겼습니다.
https://docs.google.com/spreadsheets/d/1gVuDwBqadfANoDWaRXhW104ehByASTzSpcm6-_o7pKM/edit#gid=1574734140

'페이지별 점검표'를 확인해 주시구요. 
'검수결과 이슈처리'탭에 3개정도의 에러사항 등록해 두었습니다.

**Comment by woonjjang** [comment]
@css3studio 오늘 최종 검사 부탁드려요. 마지막 이슈 처리해 두었습니다.

**Comment by woonjjang** [comment]
이슈는 닫고, 잘 통과되길 바라며 2차 심사 후 소명할 게 있으면 빠르게 공유할께요.
