### ISSUE TITLE
[영문]개선 요청

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#48]
1) 영문 node 하단의 related content 번역된 글들 노출은 잘 됩니다. 클릭시 국문으로 도달하고 있는 부분 영문으로 수정 필요합니다.
 - https://www.kyeol.kr/en/node/151
 ![스크린샷 2021-08-02 오후 12 58 07](https://user-images.githubusercontent.com/6022883/127806253-91377ae4-3632-41a6-9719-cb84c2767124.png)

2) https://kyeol.kr/en/admin/structure/taxonomy/writer/fields 저자정보 255자 제한이 걸려서, 관련 text 업데이트가 어렵습니다. 

3) (고객요청)
- footer 에 Edit: Sora Kim 영역 삭제 해 달라고 하네요. 
- contact를 주석처리하고 contact 정보를 Edit 영역으로 이동해서 4개 박스만 유지하면 어떨까요 ?
- 다시 넣어달라고 할 가능성이 있음. ;;
![하이라이트 삭제](https://user-images.githubusercontent.com/6022883/127806501-e47038bb-afc2-4841-9c1c-d990ffda2855.PNG)

**Comment by woonjjang** [comment]
1. 담당자에게는 현재 상태로 유지되고 마지막 작업 때 kyeol.kr 메뉴에 en 버튼 넣고 끝낸다고 공유해 놨어요. 
2. Resources 메뉴 목록 디자인 변경 요청 (제목만 노출해 달라는 - 디자인은 서로 조정해야 할 거라고 얘기해 놨습니다. 
- 디자인은 모조님이 편하게 하셔도 될 듯
![캡처](https://user-images.githubusercontent.com/6022883/128666973-ff30ec94-81a6-424c-b8cd-7bbf9623d691.PNG)
3. resource menu : https://github.com/team-durumi/kyeol-composer/issues/46#issuecomment-894976903

**Comment by woonjjang** [comment]
![캡처](https://user-images.githubusercontent.com/6022883/129121894-313ac9b8-9bd3-49bc-bf7e-8ee735cb32f0.PNG)


- https://github.com/team-durumi/kyeol-composer/commit/e0adca8baddc3a422d281fef98a9d6d22dca5f3a
- https://github.com/team-durumi/kyeol-composer/commit/8b6d9bfdb3ce07ca77bead0bf80d21c1c19dbd18 

요거 좀 더 수정해 달라는 요청(이미지 교체)

**Comment by woonjjang** [comment]
From 영문 웹진팀

내일 9시 전에 국문 웹진에 EN버튼만 달아주시면 될 것 같습니다.
수고해주셔서 고맙습니다!

**Comment by woonjjang** [comment]
@mozodev 

지금 Resources 게시판에 들어가서 1페이지 외 다른 페이지로 넘기면 좌측의 네 가지 카테고리가 안 보이는데, 계속 보이게 해야 할 것 같습니다.
(https://kyeol.kr/en/resources?page=2) 링크에서 보시다시피 카테고리가 사라지고 All만 남는데 그것도 클릭이 안 되는 상태입니다.

나름 오픈하는 날이라고 피드백이 잦네요. ㅎㅎ

**Comment by mozodev** [comment]
아 정말 귀찮은가 봄. 페이지 눌러볼 생각을 안했... ㅎ
https://kyeol.kr/en/resources/490?page=2

**Comment by mozodev** [comment]
저자정보 255자 제한 걸린것도 풀었....

**Comment by woonjjang** [comment]
> 1. 영문 node 하단의 related content 번역된 글들 노출은 잘 됩니다. 클릭시 국문으로 도달하고 있는 부분 영문으로 수정 필요합니다.
> 
> * https://www.kyeol.kr/en/node/151

https://github.com/team-durumi/kyeol-composer/issues/48 @mozodev 요거 적용해 주신 거 맞죠 ?

**Comment by mozodev** [comment]
이걸 quote 하고 글을 쓰는것보다 링크를 클릭해서 보는게 덜 수고스러울것 같네요 ㅋ

**Comment by woonjjang** [comment]
고생하셨습니다.
