### ISSUE TITLE
<결> 치환이슈

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#49]
[웹접근성 확인]

- 모조님 의견대로 htmlspecialchars 함수를 먼저  국,영문 적용해서 현재까지 적용한 글들에 대해서는 접근성 문제 없도록 보여지게 한다. 
- 실제로 HTML 수정을 해야 하거나 하는 글이 있으면 남겨주시면, 저나 편집팀 통해서 직접 수정할 수 있습니다. 

[영문쪽 이슈]
- & l t ; 결 & g t ; 외에도 html 꺽쇠를 사용하는데, 번역팀은 화면을 긁어나 혹은 원본파일(docx)로 번역을 합니다. 
- 잘 입력되어있거나 보여도 이후에 결과물에 다시 <결> 이라고 편집창에 넣으면 1-2년 후 접근성 체크에서 또 오류가 주루룩 나오겠죠. (뭐 우리 이슈는 아니겠지만)
- 관련해서 대체 문자열을 <결> ->  [결] 쓰는 것에 대해 8월 이후 글에 대해서 대응을 하라고 4개 편집팀에게 공지를 해 주는게 좋을 것 같습니다. 
- 우선 영문쪽 입력에서는 & l t ; 결 & g t ; 입력하는 방식으로 적용하겠습니다.  

[편집팀에게도 공지]
- 국문 편집 담당자
- 국문 외주팀
- 영문 편집 담당자
- 영문 번역팀

**Comment by mozodev** [comment]
```<결>``` 이런 상용구는 그렇게 입력하라고 하면 굉장히 짜증이 날 꺼에요. 출력할 때 한번에 치환할 수 있습니다.

**Comment by woonjjang** [comment]
@mozodev 네네 모조님 노출 항목으로는
- 제목
- 본문
- taxonomy (저자 제목, 본문) 요런 영역들 치환이 필요합니다.

**Comment by css3studio** [comment]
네 그럼, php 마크업 수정 필요시, https://docs.google.com/spreadsheets/d/1gVuDwBqadfANoDWaRXhW104ehByASTzSpcm6-_o7pKM/edit#gid=0 여기 이슈처리 탭에 남겨 놓을게요.

**Comment by css3studio** [comment]
방금 검수해 봤는데, 많이 개선 되었구요. 현재 발견되는 대부분의 문제는 글쓴이에 <>가 들어 가는 경우입니다.
![image](https://user-images.githubusercontent.com/30469662/128133171-7bc3cc31-e5df-4c89-8887-a4f88ca8b89c.png)
![image](https://user-images.githubusercontent.com/30469662/128133275-51a57689-21e1-4863-83a2-d62c05d766e5.png)

**Comment by mozodev** [comment]
일단 서버에 적용은 했어요. 제가 확인을 할 수 없어서... 이후에 진행할게 있으면 진행하시죠 ㅎ
