### ISSUE TITLE
[영문] Translate 모듈 설정 및 기본 세팅-en

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#5]
- 영문 모듈 활성화
- 페이지 매칭

Drupal 7 버전으로 관련해서 진행

**Comment by woonjjang** [comment]
https://github.com/team-durumi/kyeol-composer/commit/d277ddbbbd25d4c8a5d191329ade45d6586f6ab4

**Comment by woonjjang** [comment]
@mozodev 질문있습니다. 
태그쪽 화면 구성은 동일하니깐 별로 질문이 없는데, content 쪽처럼 Taxanomy/term 쪽도 매칭되게 영문 입력해주는 영역이 있을까요?
혹은 별도의 모듈 작업이 있어야 하다면 알려주셔도 됩니다. 

http://kyeol.durumi.io/en/taxonomy/term/70

**Comment by mozodev** [comment]
http://kyeol.durumi.io/en/taxonomy/term/70/translate
