### ISSUE TITLE
[kyeol] 정보시스템 점검

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#50]
20210-8-3-09:00 부로 사이버위기 ‘관심’ 경보가 발령됨에 따라 정보보호시스템 및 정보시스템에 대한 해킹징후 및 정상작동 여부, 접속․이용에 특이사항이 있는지 확인하시고 점검결과를 알려주시기 바랍니다.

한글문서

**Comment by mozodev** [comment]
[정보시스템 등 점검표 .pdf](https://github.com/team-durumi/kyeol-composer/files/6952398/default.pdf)
