### ISSUE TITLE
뉴스레터 -> 외부 netlify 쪽으로 제거한다.

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#51]
넷리파이에 서비스하는 것이나 스티비에 기존 url을 쓰는 것이나 동일해서
https://github.com/team-durumi/kyeol-composer/commit/9d8f3d24a418737ffa3847c78921a32e685df14b

**Comment by mozodev** [comment]
https://kyeol.kr/newsletters

**Comment by woonjjang** [comment]
뉴스레터를 외부 링크로 빼는 것에 진흥원쪽 허가는 받은 것으로 보이구요. 다음주 월요일 팀장님 복귀하시면 최종 컨펌해 준다고 하네요. 그거 확인하면 html 지우시죠.
