### ISSUE TITLE
[서버/DB] 취약점검

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#53]
검토 후 금주 내 제출 불가 시 회신 부탁드립니다.

○ 요청내용

1. 모든 서버 (DB 포함) 스크립트 실행 후 결과파일

   * 첨부 zip 파일 내 진단도구와 사용가이드가 있습니다.

2. 진흥원 시스템이 연결된 IP 부여된 네트워크장비 config 파일

   * 대표적인 cisco 장비 경우, show running-config(show run) 명령어 입력

○ 대상 시스템 서버

   * 가비아 : 대표홈페이지 1식, 그룹웨어 2식, 위기청소년 2식, 웹진 결 1식 
   * 기가오피스 : 사이버상담 1식 
   * kt 클라우드 : 해바라기정보시스템 3식, 종사자교육포털 2식, 업무포털 1식 
   * 코드라인 : 삭제시스템  3식 
   * 연구소 : 아카이브 1식, 웹진 결 1식

○ 관련문의

   * 서버 IP 등 시스템 정보 확인 관련 문의 : 진흥원 손지미 02-6363-8337 

   * 스크립트 관련 등 기술문의 : LnJ 테크 황민정 주임 010-6391-8197

**Comment by woonjjang** [comment]
@mozodev stopmaster 서버에서 순서대로 해 보고 있는데요. 
`MySQL my.cnf 경로 확인` -> 부분에서 아래 3개 경로를 넣어도 스크립트가 안 돌아가네요.  

/etc/mysql/my.cnf
/etc/mysql/conf.d
/etc/mysql/mariadb.conf.d/

mariadb 여서 해당 테스트 항목에 없을 수도 있을 수도 있는데, 혹시 설정 파일로 지정해야할 대상을 아시면 도움을 좀 주십시요.

**Comment by mozodev** [comment]
[diagnosis-kyeol-kr.tar.gz](https://github.com/team-durumi/kyeol-composer/files/7166935/diagnosis-kyeol-kr.tar.gz)

**Comment by mozodev** [comment]
논쟁의 여지가 있는 부분들이 많기는 하지만 뭐 까라고 하고 까야지요 ㅋ
그런데 이 짓도 날이갈수록 격렬해지는군요. ㅎ

**Comment by woonjjang** [comment]
연구소가 힘이 없어서, ㅎㅎ
도움 감사합니다. 다시 까라고 할 때까지 close
