### ISSUE TITLE
국문사이트 디자인 및 기능 개선

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#56]
붙임. 2021년 웹진 결 국문사이트 디자인 및 기능 개선 기획(안)

1. 메인페이지 삼단줄 표시 클릭 후 왼쪽에 표시되는 웹진 결 메뉴를 아래 사이트와 같이 상단메뉴로 배치하고자 함, 또한 특집 콘텐츠를 묶어 볼 수 있는 ‘특집’ 카테고리 메뉴에 추가 요청 
-  메뉴 펼치는데, 2뎁스 메뉴가 있으므로 좀 논의해 보라고 함. 
-  특집 | 인터뷰 | 에세이 | 논평 | 좌담 | 자료해제 | 엮어보기 [ 검색 / 영문]

2. 메인페이지 상단 스페이스 내 날짜 및 발행 호 기입 요청
- 데이터가 있는데, 노출되지 않아서 해당 node에 대한 정보를 더 노출해 달라고 하는 의도
- 작성일 / 저자 / 어떤 카테고리 글인지? / volume은 없어졌으니

3. 메인페이지/ 본문 내 좌우 빈 여백을 채울 수 있는 디자인으로 수정 필요
- 반응형으로 만들어져 있다는 사실을 설명함. 
- 해상도 높을 때 글 요소를 변경하고, 영문처럼 영역을 잡아서 노출해 주는 방식으로 구성을 해야 할 것으로 보임. 

4. 웹진 결 콘텐츠 본문 하단 측 SNS 공유건 링크 개발 
- 내용 그대로

5. 참고 사이트
문학광장 웹진 :　https://webzine.munjang.or.kr/
Korea webzine : https://www.kocis.go.kr/eng/webzine/201802/index.html

------------
취약점검 작업 1주 / 영문쪽에 화면들 좀 잔여가 있으니, 보너스라고 생각하고 시도함이 어떨런지 ㅎㅎ
12월 3일까지로 계약 잡았습니다.

**Comment by mozodev** [comment]
## 1. navbar 노출

메인페이지 삼단줄 표시 클릭 후 왼쪽에 표시되는 웹진 결 메뉴를 아래 사이트와 같이 상단메뉴로 배치하고자 함 또한 특집 콘텐츠를 묶어 볼 수 있는 특집 카테고리 메뉴에 추가 요청

## 2. 메인페이지 상단 스페이스 내 날짜 및 발행 호 기입 요청

콘텐츠의 업로드 일자 저자 콘텐츠 발행호수 등이 표시될 수 있는 디자인 수정 필요

## 3. 메인페이지 본문 내 좌우 빈 여백을 채울 수 있는 디자인으로 수정 필요

## 4. 웹진 결 콘텐츠 본문 하단 측 공유건 링크 개발
- [ ] https://www.kocis.go.kr/eng/webzine/201802/sub03.html 에 있는 공유버튼 / 
- 위치와 관련해서는 현재 링크 복사하는 부분이 있는데, 위치는 모조님 맘데로 잡아주셔도 될 듯 합니다. 

## 5. 참고 사이트

- 문학광장 웹진 :　https://webzine.munjang.or.kr/
- Korea webzine : https://www.kocis.go.kr/eng/webzine/201802/index.html

## 6. 확인할 수 있는 링크 
- ngrok 이나 확인할 수 있는 링크로 띄워서 보여주는 것만 담주 화요일에 처리되면 될 듯 
- 어차피 미팅 전후에 피드백이 있을 듯 하고, 최종 적용은 만난 이후에 처리

## 7. 보고 및 문서 @woonjjang 
- [x] 요번 변경작업 완료보고서 / 행정문서 전달(30일)
- [x] 국문 운영관련 완료보고서 / 행정문서 전달(30일) / 땡겨서 처리해주겠다. -> 담당자가 12/3 내부 보고 정리
- [x] 실제 의견 및 수정은 12/06 - 12/10 사이에 만나서 보고하고 처리하자.

**Comment by mozodev** [comment]
![1920-1](https://user-images.githubusercontent.com/1661950/143977203-54d2e1c8-0973-47ec-b8b1-6c22434c00a9.png)
![1920-2](https://user-images.githubusercontent.com/1661950/143977216-0c30dc43-b6f5-4962-8480-2131c6d44f44.png)

도대체 왜 패널을 썼는지는 정말 모르겠고 알고 싶지 않고...
나머지는 이해는 되는데 지금쯤이면 이렇게 코드를 쓰지는 않겠지... ㅎ

**Comment by mozodev** [comment]
<img width="1435" alt="node-436" src="https://user-images.githubusercontent.com/1661950/143980170-ce0dcf7e-6e7b-4bb3-901a-77e6294dfee7.png">

**Comment by mozodev** [comment]
![1920-front-full](https://user-images.githubusercontent.com/1661950/143980581-877428a0-16c5-44a0-8be3-35436397c8a4.png)

**Comment by woonjjang** [comment]
단건 작업 완료보고서 (12.03) https://docs.google.com/document/d/1txm5oTdAKU2VB48BZIzG2ExfNtUVvPSUO-5rjdHgoLM/edit#heading=h.23a2vd31egt1

**Comment by mozodev** [comment]
```
https://d3a0-61-73-10-147.ap.ngrok.io/
kyeol:20211206
```
