### ISSUE TITLE
특집(featured)태그 단어 목록 노출

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#57]
12월 7일 미팅에서 요구사항 확인하고 시작하시죠. 

## 엮어보기 메뉴

○ 카테고리 내 숨겨져 있는 ‘엮어보기’ 메뉴를 ‘해시태그’로 명칭 변경하여 메인페이지 상단 부분에 추가함으로써 가시화, 활성화하고자 함.   
○ 하나의 태그와 관련된 글만 볼 수 있는 현 엮어보기 기능을 다중적 해시태그 검색옵션 형식으로 변경, 최적의 콘텐츠를 보여주는 기능으로 고도화하고자 함. 

## 해시태그 검색 기능 예시 아래 
○ 다수 태그가 선택된 결과값을 보여주는 것과 화면을 요청하는 것으로 보임.

## 해시태그 기능 아이콘을 누르면 아래와 같이 맵 디자인 형식의 반투명창이 펼쳐지는 플래시를 제작하고자 함. (플레시 제작은 안 함.)

**Comment by mozodev** [comment]
<img width="631" alt="스크린샷 2022-01-03 오후 2 36 50" src="https://user-images.githubusercontent.com/1661950/148000628-ae0d86a3-7bfb-4090-bb78-09deb891ef81.png">

![image](https://user-images.githubusercontent.com/1661950/148000669-912505c9-8652-45b6-a7f8-3903aae85841.png)

**Comment by mozodev** [comment]
- 1~3월 중 키워드(태그) 정리할 예정
- 엮어보기 > 특집 vocabulary 생성해서 정리, GNB 메뉴 추가
- 특집 키워드에 5개 기사 연결
- 초기 화면 - 썸네일 없애고 각 카테고리별로 글 제목과 저자로만 더 많이 노출하면 좋겠다.
- 웹사이트에 많은 콘텐츠가 있다는 사실을 초기 화면에서 사용자가 바로 알 수 있으면 좋겠다.

**Comment by woonjjang** [comment]
### 개발환경은 다 구축 못 한 상태여서, 우선 관리화면에서 Site-Build
- 전달받은 엑셀 : https://docs.google.com/spreadsheets/d/1JXrqjHv1vl1pprz3z5iZsb57I6Yu-Nrm/edit?usp=sharing&ouid=109708625703467088036&rtpof=true&sd=true
- [x] featured(taxonomy 생성 및 추가)https://kyeol.kr/ko/admin/structure/taxonomy/featured
- [x] article (contents type에 해당 필드 추가) https://kyeol.kr/ko/admin/structure/types/manage/article/fields
- [x] 엑셀목록대로 콘텐츠 수정 완료 (52건)

### 화면정리
- [ ] GNB 메뉴 추가 - 특집
- [ ] 특집 화면은 (term 뷰 - 화면이 없긴해서) & 화요일 만나서 논의

### 협의 어려운 부분 #58 (별도 논의)
- [ ] 초기 화면 - 썸네일 없애고 각 카테고리별로 글 제목과 저자로만 더 많이 노출하면 좋겠다.
- [ ] 웹사이트에 많은 콘텐츠가 있다는 사실을 초기 화면에서 사용자가 바로 알 수 있으면 좋겠다.

view 화면 부분 만드는 것은 내일 같이 해 보면 좋겠습니다.

**Comment by mozodev** [comment]
사이트 빌딩이야 원래 드루팔 7에서는 운영에서 하는게 맞습니다. 개발 환경에서 해도 운영으로 옮길 방법이 없으니까요
8부터는 코드로 사이트 빌딩 내역을 export 해서 운영에서 import 하면 동일하게 반영이 됩니다.
일단 내일 오후에 개발 환경을 같이 만들어보죠 ㅎ 

https://github.com/team-durumi/kyeol-composer/tree/main/.devcontainer
이게 있는 걸로 보아 codespace에서 돌렸던 거 같은데 기억이 가물가물하네요 ㅎ 
현재는 프로비저닝 코드는 codespace, gitpod, vagrant 가 다 들어있기는 하네요. multipass 가 없...

아 로그를 보니 오늘 오후부터 계속 codespace와 씨름을 하셨...
db 복원이 어려웠을까요? ㅎㅎ 암튼...

**Comment by woonjjang** [comment]
composer & drush도 익숙하지 않아서 ㅎㅎ
낼 오후에 좀 도와주세요 ~

**Comment by mozodev** [comment]
### 기사분류
https://kyeol.kr/ko/admin/structure/taxonomy/article_category

- 인터뷰 https://kyeol.kr/category/인터뷰
- 에세이 https://kyeol.kr/category/에세이
- 논평 https://kyeol.kr/category/논평
- 좌담 https://kyeol.kr/category/좌담
- 자료해제 https://kyeol.kr/category/자료해제

### featured 분류
https://kyeol.kr/ko/admin/structure/taxonomy/featured

- [x] 목록 화면 추가 https://kyeol.kr/featured
- [ ] 사이드바에 특집 term 목록 추가
- [x] GNB 메뉴 추가
- [x] GNB 주 메뉴에도 특집 추가(순서 조정)

[포토에세이] 역사의 뒤안길에서 만난 조선인 피해자들
https://kyeol.kr/ko/category/%ED%8F%AC%ED%86%A0%EC%97%90%EC%84%B8%EC%9D%B4-%EC%97%AD%EC%82%AC%EC%9D%98-%EB%92%A4%EC%95%88%EA%B8%B8%EC%97%90%EC%84%9C-%EB%A7%8C%EB%82%9C-%EC%A1%B0%EC%84%A0%EC%9D%B8-%ED%94%BC%ED%95%B4%EC%9E%90%EB%93%A4
- [포토에세이] 역사의 뒤안길에서 만난 조선인 피해자들 05. 박차순 이야기
- [포토에세이] 역사의 뒤안길에서 만난 조선인 피해자들 04. 박우득 이야기
- [포토에세이] 역사의 뒤안길에서 만난 조선인 피해자들 03. 백넙데기 이야기
- [포토에세이] 역사의 뒤안길에서 만난 조선인 피해자들 02. 배삼엽 이야기
- [포토에세이] 역사의 뒤안길에서 만난 조선인 피해자들 01. 이수단 이야기

**Comment by mozodev** [comment]
google `drupal 7 term template by vocabulary`
=> https://www.drupal.org/forum/support/theme-development/2011-10-18/making-a-template-file-for-terms-in-a-vocabulary-in#comment-7827895

```php
function MYTHEME_preprocess_page(&$variables) {  

  if (arg(0) == 'taxonomy' && arg(1) == 'term' )
  {
    $term = taxonomy_term_load(arg(2));
    $vocabulary = taxonomy_vocabulary_load($term->vid);
    $variables['theme_hook_suggestions'][] = 'page__taxonomy_vocabulary_' . $vocabulary->machine_name;
  }
}
```

**Comment by mozodev** [comment]
주의할 점... 일반 기사와 위계 구조가 다름. 
vocabulary: article_category
terms: 인터뷰, 에세이, 논평, 좌담, 자료해제

특집
vocabulary: featured
terms: [포토에세이] 역사의 뒤안길에서 만난 조선인 피해자들, + N

메뉴에서 인터뷰 클릭하면 나오는 화면은 
/category/인터뷰 => 인터뷰 기사 목록

특집은 이렇게 안됨 
/featured/ => 특집 분류 term 목록 <= 이건 어떻게? vocabulary 안에 있는 텀 목록이 나아야 함. create new views!
term => /ko/category/포토에세이-역사의-뒤안길에서-만난-조선인-피해자들 기사 목록

**Comment by woonjjang** [comment]
모조님 코멘트 감사합니다. 

생각은 비슷하게 가고 있는데요. 
article_category 랑 엮어보기랑도 위계가 안 맞아서, 별로 페이지와 sidebar를 잡아주려고 했습니다. 
article / archives / en-resources 3가지 구현된 것 보면서 어떤 방식이 좋을까 해 보고 있었네요. ㅎㅎ

근데, 특집 /featured/ 1개 목록에 sidebar도 안 어울리는 것 같아서

https://kyeol.kr/back-issues
https://kyeol.kr/ko/vol/2021

방식으로 시도해 볼까 합니다. 제언데로 
/featured 새로운 뷰를 만들고
slowalk.inc 파일에 선언하고
tpl 파일 생성하고 

요렇게 해 보려고 합니다.

**Comment by mozodev** [comment]
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/1661950/153982594-0c19fa33-9f7b-4416-b377-c887ec3c14b8.png">

https://github.com/team-durumi/kyeol-composer/tree/feature/featured

**Comment by mozodev** [comment]
https://kyeol.kr/ko/category/%ED%8F%AC%ED%86%A0%EC%97%90%EC%84%B8%EC%9D%B4-%EC%97%AD%EC%82%AC%EC%9D%98-%EB%92%A4%EC%95%88%EA%B8%B8%EC%97%90%EC%84%9C-%EB%A7%8C%EB%82%9C-%EC%A1%B0%EC%84%A0%EC%9D%B8-%ED%94%BC%ED%95%B4%EC%9E%90%EB%93%A4
저는 이 화면에서 사이드바만 특집 목록 화면의 최신 10개 글만 노출하면 되지 않을까하고 생각하고 있었...

그러면 현재 인터뷰 기사 화면에는 블록으로 메뉴를 출력하고 있는거라.. 특집 최신 10개 뷰 블록 추가하고
pathauto 모듈로 url alias를 featured vocabulary에 있는 아이들만 
/featured/s(eries)/{{ term_id }} 나
/featured/{{ term_id }}
이런 식으로 걸고
/featured/series/* 경로에만 블록을 노출하게 하면 템플릿 고치지 않고 클릭해서 일단 원하는 화면을 얻을 수도...

**Comment by woonjjang** [comment]
[실패]
- 정신없이 하다가 production 에다가 featued-list 뷰를 만들었습니다.(삭제는 안 했음.)
- featured view를 삭제하거나, 했을 경우 혹은 중복 생성할 시에 문제가 있다고 했던게 기억나서 -> rebuild / 개발환경 새로 시작 ㅎㅎ
- 화면 데이터를 불러오는게 모르는 부분이 많아서, 모조님이 조언해주신대로 방향을 틀었구요. 
- featured-list-test를 만들어서 우선 테스트중입니다.

[제언해주신 방향대로]
- pathauto 모듈은 어디있지 ? 찾다가 / module/contrib에 있으니 GUI메뉴에서 찾아서 설정에 들어감.
- /ko/admin/config/search/path/patterns /featured/{{ term_id }}
- url alias를 설정했으나 ... 연결은 안 되네요. 

시간이 되시면 콜 한 번 나누면 좋겠습니다. :-) @mozodev

**Comment by woonjjang** [comment]
[배포]
- https://kyeol.kr/featured
- https://kyeol.kr/ko/featured/%EA%B9%80%EC%88%A8-%EC%9E%91%EA%B0%80-%ED%8A%B9%EC%A7%91

**Comment by woonjjang** [comment]
일주일이 지났는데, 피드백이 없다 !! (맘에 드는 거겠지 ㅎㅎ)
