### ISSUE TITLE
메인 하단 글 노출 영역 에러 

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#59]
https://kyeol.kr/ko/admin/webzine

슬라이드쪽 아니고, 메인 하단에 글 뿌리는 영역이 오류가 생기는 것으로 보입니다. 
연구소에서 2022년으로 바꾸로 업데이를 한 것으로 보여요. 
연도별 node가 아예 없는 상태는 아닌 것으로 보입니다.

우선 글이 나오게 해 주는 상태로 돌려놓으면 될 듯 합니다.

**Comment by mozodev** [comment]
첫 화면에 두 개씩 뿌리도록 수정하고 관리자 화면도 수정을 했어야했는데 몰랐네요. 거기서도 같은 함수로 호출할 줄이야.. ㅎ
2022년에 글이 없어서 2021년으로 해놓고 저장했습니다.
