### ISSUE TITLE
[영문] Glossary 외 Tag 영역 5개 페이지 (전문용어/동일기능)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#6]
team-durumi/kyeol#3 국문페이지에 개발하는 전문용어 페이지와 동일한 영문 버전

(용어창)
- 현재 특정 용어에 커서를 대면 그냥 삽입해 놓은 용어 설명창이 열리는데
- 영문에서는 클릭하면 Glossary 페이지에 해당 용어 부분이 열리도록 구현

Taxanomy
- 국문 용어도 단어묶음으로 관리
- 영문도 관련 단어묶음으로 관리

에디터에서 영문쪽 용어를 찾아서 지정하는 부분까지 설정이 필요함.

(개발 시나리오)
- 전문용어 필드에 해당 키워드를 입력한다. (제목 / 본문) http://kyeol.kr/admin/structure/taxonomy/terms
- 본문에 있는 텍스트를 적고, 저장해서 실제 전문용어에 해당되는 Term에 일치하는게 있으면, 기존과 같은 전문용어 스타일로 보여준다. (따라서 에디터창에서 별도로 추가하거나 저장할 필요는 없다.)
- 요약하면 글만쓰고 저장하면 전문용어 팝업 모양이 노출된다.(cavac notify)

(디자인 레이아웃)
- http://kyeol-en.durumi.io/html-en/02_collect_list_glossary.html

**Comment by woonjjang** [comment]
- 영문 전문용어 예제 샘플글 수급(09.09) :  https://drive.google.com/file/d/1kbwrzGPLEOH0NDwUHEX5fb_yOH1FtYAL/view?usp=sharing
- 전문용어 Voca에 묶여있는 단어(term)들은 국문 - 영문 연계가 될 수 있다.(개발 시나리오 확인)
- 번역된 영문 Glossary 샘플 :  https://drive.google.com/file/d/1dcDygXqUJNILk1nBAEB10QiWCzeeCdzC/view?usp=sharing

**Comment by woonjjang** [comment]
Sort by – Person / Subject / Region / Writer / Glossary

**Comment by woonjjang** [comment]
http://www.kyeol.kr/en/taxonomy/term/21/edit/add/ko/en

영문 term 설명 입력시 255 제한 에러 풀어주시면 감사하겠습니다.

**Comment by mozodev** [comment]
Long text and summary 이거라 그런 제한이 없는데요 이상하네요

**Comment by woonjjang** [comment]
요거 넣는 중
```
Park-Kim Wooki (朴金優綺 / ぱくきむ・うぎ). She is a third-generation Korean in Japan and a human rights activist. She also serves as a secretariat staff person at the Human Rights Association for Korean Residents in Japan (HURAK), a lecturer at Chosun University, and a singer. Her activities primarily focus on the resolution of issues related to the Japanese military sexual slavery and the human rights of Koreans in Japan, including discrimination against Korean schools in Japan. She participated as Japan's first panelist at the <Forum on Minority Issues> hosted by the United Nations, in which she presented a report on the education rights of Korean children in Japan (in 2017).
```

**Comment by woonjjang** [comment]
```
http://www.kyeol.kr/en/archive/person
http://www.kyeol.kr/en/archive/tags
http://www.kyeol.kr/en/archive/location
http://www.kyeol.kr/en/archive/writer
http://www.kyeol.kr/en/archive/terms
```
@mozodev 이 중에 person 만 자체 개발되어 있는거 맞죠 ?

**Comment by woonjjang** [comment]
넣어놓은 목록이 내일 잘 보이기만 해도 좋겠습니다. (view화면에 영문 조건 추가했는데, 자동으로 나오진 않은 듯)

**Comment by mozodev** [comment]
어떤 뷰를 말씀하시는지? content:language 가 아니고 title_field:language 입니다. entity translation을 쓰면 이렇게 됩니다.

**Comment by woonjjang** [comment]
> 어떤 뷰를 말씀하시는지?

http://www.kyeol.kr/en/admin/structure/views/view/archive_view/edit/writer?destination=archive/writer

**Comment by mozodev** [comment]
http://www.kyeol.kr/en/archive/person
http://www.kyeol.kr/en/archive/tags
http://www.kyeol.kr/en/archive/location
http://www.kyeol.kr/en/archive/writer
http://www.kyeol.kr/en/archive/terms

이 화면에 태그가 국문으로 보이는거 땜에 그러시는거면 이건 확인해보니 번역이 안되어 있어서 그런것 같아요

김복동 태그 번역이 안되어 있습니다.
http://www.kyeol.kr/en/taxonomy/term/70/translate

말레이시아 태그 번역이 안되어 있습니다.
http://www.kyeol.kr/en/taxonomy/term/320/translate

http://www.kyeol.kr/en/archive/writer
이 화면은 뷰에 문제가 있는거 같아요. 제목언어로 영어를 지정해도 국문이 돌아오는데 원인이 파악이 안됩니다.

**Comment by woonjjang** [comment]
전체적으로 최종 번역 안 되어 있는게 맞습니다. https://github.com/team-durumi/kyeol-composer/issues/25
인물중에는 일부분 번역되어 있고, Term(전문용어) 는 전체 번역이 되어 있어요. http://www.kyeol.kr/en/archive/terms
