### ISSUE TITLE
[영문] '일본군'위안부 소개 페이지

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#7]

**Comment by woonjjang** [comment]
연구소 아카이브에 소개글 : https://www.archive814.or.kr/About/Define
http://www.hermuseum.go.kr/main/PageLink.do 참고 부탁드립니다.

**Comment by woonjjang** [comment]
원고 수급(09/09) : https://docs.google.com/document/d/1y1BI-O7T17BCzD135-5Kcl0zMRM5Qwrl/edit#heading=h.oqsp494k7b3f**

**Comment by mozodev** [comment]
http://kyeol.durumi.io/en/comfort-women

**Comment by woonjjang** [comment]
![스크린샷 2020-11-27 오후 5 59 13](https://user-images.githubusercontent.com/6022883/100430635-64f95e00-30da-11eb-973c-ad2b8159c1ca.png)

경로값으로 첫 Title 이 표현되는 것 같은데 "Comfort Women" 으로 노출되어야 합니다. 
그 외에는 이슈가 없습니다. 고생하셨습니다.

**Comment by woonjjang** [comment]
지도 및 출처 표시 
>> *위안소 지도 출처표기:  "(c)Women's Active Museum on War and Peace" (https://wam-peace.org/ianjo/)

**Comment by mozodev** [comment]
http://www.kyeol.kr/en/comfort-women
http://www.kyeol.kr/en/rimss
http://www.kyeol.kr/en/kyeol
