### ISSUE TITLE
[영문] '일본군'위안부문제연구소 소개 페이지

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kyeol-composer#9]
https://docs.google.com/document/d/1y1BI-O7T17BCzD135-5Kcl0zMRM5Qwrl/edit#heading=h.5j6etuf6xxph

현재 국문 결 소개 부분이 원본이니 참고 부탁드리겠습니다. 아래 글들은 모두 최종본이 아니므로 추후 내용이 변경될 수 있습니다

**Comment by woonjjang** [comment]
Introduction 

Research Institute on Japanese Military Sexual Slavery(RIMSS) 
Reseach Institute on Japanese Military Sexual Slavery(RIMSS) was established in year 2018 to advance gender equality and women’s human rights. It supports projects aimed at preventing and eradicating violence against women, as well as providing victim-support. Since 2018 the Institute has been keen on conducting systematic research on the issue of Japanese military sexual slavery. 

RIMSS’s webzine, Kyeol*, aims to provide comprehensive coverage using a variety of sources. Its mission is to actively encourage research activities and deepen public understanding of sexual slavery victims. It furnishes content in the form of articles, field reports, essays, interviews, and archive reviews, in order to raise awareness of the military sexual slavery issue in both Korea and abroad and help promote women’s human rights around the world.   

* [Translator Note] Kyeol is a Korean word referring to the layerof a fabric, or a distinct pattern or texture which has developed on the surface of wood, stone or skin.

- 각주가 포함되어 있음.

**Comment by mozodev** [comment]
http://kyeol.durumi.io/en/rimss
